-- MySQL Script generated by MySQL Workbench
-- vie 30 ago 2019 23:26:13 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cineV2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cineV2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cineV2` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `cineV2` ;

-- -----------------------------------------------------
-- Table `cineV2`.`asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`asiento` (
  `id_asiento` INT(11) NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_asiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`sucursal` (
  `id_sucursal` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `contacto` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cineV2`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`sala` (
  `id_sala` INT(11) NOT NULL AUTO_INCREMENT,
  `id_sucursal` INT(11) NOT NULL,
  `sala` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sala`),
  INDEX `fk_sala_sucursal1_idx` (`id_sucursal` ASC),
  CONSTRAINT `fk_sala_sucursal1`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `cineV2`.`sucursal` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`asiento_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`asiento_sala` (
  `id_asiento` INT(11) NOT NULL,
  `id_sala` INT(11) NOT NULL,
  `fila` VARCHAR(45) NOT NULL,
  `columna` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_asiento`),
  INDEX `fk_asiento_has_sala_sala1_idx` (`id_sala` ASC),
  INDEX `fk_asiento_has_sala_asiento1_idx` (`id_asiento` ASC),
  CONSTRAINT `asiento_sala_ibfk_1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `cineV2`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asiento_has_sala_asiento1`
    FOREIGN KEY (`id_asiento`)
    REFERENCES `cineV2`.`asiento` (`id_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`caracteristica_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`caracteristica_asiento` (
  `id_caracteristica` INT(11) NOT NULL,
  `caracteristica` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_caracteristica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`atributo_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`atributo_asiento` (
  `id_caracteristica` INT(11) NOT NULL,
  `id_asiento` INT(11) NOT NULL,
  `valor` INT(11) NOT NULL,
  PRIMARY KEY (`id_caracteristica`, `id_asiento`),
  INDEX `fk_atributo_asiento_caracteristica_asiento1_idx` (`id_caracteristica` ASC),
  INDEX `fk_atributo_asiento_asiento1_idx` (`id_asiento` ASC),
  CONSTRAINT `fk_atributo_asiento_asiento1`
    FOREIGN KEY (`id_asiento`)
    REFERENCES `cineV2`.`asiento` (`id_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atributo_asiento_caracteristica_asiento1`
    FOREIGN KEY (`id_caracteristica`)
    REFERENCES `cineV2`.`caracteristica_asiento` (`id_caracteristica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`caracteristica_funcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`caracteristica_funcion` (
  `id_caracteristica` INT(11) NOT NULL,
  `caracteristica` VARCHAR(300) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_caracteristica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`clasificacion` (
  `id_clasificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `clasificacion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_clasificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cineV2`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`director` (
  `id_director` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_director`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cineV2`.`pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`pelicula` (
  `id_pelicula` INT(11) NOT NULL AUTO_INCREMENT,
  `id_director` INT(11) NOT NULL,
  `id_clasificacion` INT(11) NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `fecha_estreno` DATE NOT NULL,
  `sinopsis` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_pelicula`),
  INDEX `fk_pelicula_director1_idx` (`id_director` ASC),
  INDEX `fk_pelicula_clasificacion2_idx` (`id_clasificacion` ASC),
  CONSTRAINT `fk_pelicula_clasificacion2`
    FOREIGN KEY (`id_clasificacion`)
    REFERENCES `cineV2`.`clasificacion` (`id_clasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelicula_director1`
    FOREIGN KEY (`id_director`)
    REFERENCES `cineV2`.`director` (`id_director`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`funcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`funcion` (
  `id_funcion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pelicula` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_funcion`),
  INDEX `fk_funcion_pelicula1_idx` (`id_pelicula` ASC),
  CONSTRAINT `fk_funcion_pelicula1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `cineV2`.`pelicula` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`atributo_funcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`atributo_funcion` (
  `id_caracteristica` INT(11) NOT NULL,
  `id_funcion` INT(11) NOT NULL,
  `valor` INT(11) NOT NULL,
  PRIMARY KEY (`id_funcion`, `id_caracteristica`),
  INDEX `fk_atributo_funcion_caracteristica_funcion1_idx` (`id_caracteristica` ASC),
  INDEX `fk_atributo_funcion_funcion1_idx` (`id_funcion` ASC),
  CONSTRAINT `fk_atributo_funcion_caracteristica_funcion1`
    FOREIGN KEY (`id_caracteristica`)
    REFERENCES `cineV2`.`caracteristica_funcion` (`id_caracteristica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atributo_funcion_funcion1`
    FOREIGN KEY (`id_funcion`)
    REFERENCES `cineV2`.`funcion` (`id_funcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`caracteristica_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`caracteristica_sala` (
  `id_caracteristica` INT(11) NOT NULL AUTO_INCREMENT,
  `caracteristica` VARCHAR(300) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_caracteristica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`atributo_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`atributo_sala` (
  `id_caracteristica` INT(11) NOT NULL,
  `id_sala` INT(11) NOT NULL,
  `valor` INT(11) NOT NULL,
  PRIMARY KEY (`id_caracteristica`, `id_sala`),
  INDEX `fk_atributo_sala_caracteristica_sala_idx` (`id_caracteristica` ASC),
  INDEX `fk_atributo_sala_sala1_idx` (`id_sala` ASC),
  CONSTRAINT `fk_atributo_sala_caracteristica_sala`
    FOREIGN KEY (`id_caracteristica`)
    REFERENCES `cineV2`.`caracteristica_sala` (`id_caracteristica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atributo_sala_sala1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `cineV2`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`tipo_descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`tipo_descuento` (
  `id_tipo_descuento` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `aplicable_boleto` TINYINT(1) NOT NULL,
  `aplicable_consumible` TINYINT(1) NOT NULL,
  `porcentaje_sugerido` DOUBLE NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_tipo_descuento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`descuento` (
  `id_descuento` INT(11) NOT NULL AUTO_INCREMENT,
  `id_tipo_descuento` INT(11) NOT NULL,
  `porcentaje` DOUBLE NOT NULL,
  PRIMARY KEY (`id_descuento`),
  INDEX `fk_descuento_tipo_descuento1_idx` (`id_tipo_descuento` ASC),
  CONSTRAINT `fk_descuento_tipo_descuento1`
    FOREIGN KEY (`id_tipo_descuento`)
    REFERENCES `cineV2`.`tipo_descuento` (`id_tipo_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`factura` (
  `id_factura` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `caja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_factura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`genero` (
  `id_genero` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cineV2`.`genero_pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`genero_pelicula` (
  `id_genero` INT(11) NOT NULL,
  `id_pelicula` INT(11) NOT NULL,
  PRIMARY KEY (`id_genero`, `id_pelicula`),
  INDEX `fk_pelicula_has_genero_genero1_idx` (`id_genero` ASC),
  INDEX `fk_pelicula_has_genero_pelicula1_idx` (`id_pelicula` ASC),
  CONSTRAINT `fk_pelicula_has_genero_genero1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `cineV2`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelicula_has_genero_pelicula1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `cineV2`.`pelicula` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`menu_consumible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`menu_consumible` (
  `id_consumible` INT(11) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`id_consumible`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`orden` (
  `id_orden` INT(11) NOT NULL AUTO_INCREMENT,
  `id_descuento` INT(11) NOT NULL,
  `monto_total` DOUBLE NULL,
  PRIMARY KEY (`id_orden`),
  INDEX `fk_orden_descuento1_idx` (`id_descuento` ASC),
  CONSTRAINT `fk_orden_descuento1`
    FOREIGN KEY (`id_descuento`)
    REFERENCES `cineV2`.`descuento` (`id_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cineV2`.`orden_consumible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`orden_consumible` (
  `id_orden` INT(11) NOT NULL,
  `id_consumible` INT(11) NOT NULL,
  `cantidad` INT(4) NOT NULL,
  `monto_total` DOUBLE NOT NULL,
  PRIMARY KEY (`id_orden`, `id_consumible`),
  INDEX `fk_orden_consumible_menu_consumible1_idx` (`id_consumible` ASC),
  INDEX `fk_orden_consumible_orden2_idx` (`id_orden` ASC),
  CONSTRAINT `fk_orden_consumible_menu_consumible1`
    FOREIGN KEY (`id_consumible`)
    REFERENCES `cineV2`.`menu_consumible` (`id_consumible`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_consumible_orden2`
    FOREIGN KEY (`id_orden`)
    REFERENCES `cineV2`.`orden` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`tipo_pago` (
  `id_tipo_pago` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_pago` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_tipo_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`pago` (
  `id_pago` INT(11) NOT NULL AUTO_INCREMENT,
  `id_tipo_pago` INT(11) NOT NULL,
  `monto` DOUBLE NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_pago_tipo_pago1_idx` (`id_tipo_pago` ASC),
  CONSTRAINT `fk_pago_tipo_pago1`
    FOREIGN KEY (`id_tipo_pago`)
    REFERENCES `cineV2`.`tipo_pago` (`id_tipo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `cineV2`.`pago_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`pago_factura` (
  `id_pago` INT(11) NOT NULL,
  `id_factura` INT(11) NOT NULL,
  PRIMARY KEY (`id_pago`, `id_factura`),
  INDEX `fk_pagoPorFactura_1_idx` (`id_factura` ASC),
  INDEX `fk_pagoPorFactura_2_idx` (`id_pago` ASC),
  CONSTRAINT `fk_pagoPorFactura_1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `cineV2`.`factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagoPorFactura_2`
    FOREIGN KEY (`id_pago`)
    REFERENCES `cineV2`.`pago` (`id_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cineV2`.`boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`boleto` (
  `id_boleto` INT(11) NOT NULL,
  `id_funcion` INT(11) NOT NULL,
  `id_asiento` INT(11) NOT NULL,
  `id_descuento` INT(11) NOT NULL,
  `precio_base` DOUBLE NULL,
  PRIMARY KEY (`id_boleto`),
  INDEX `fk_boleto_1_idx` (`id_funcion` ASC),
  INDEX `fk_boleto_2_idx` (`id_asiento` ASC),
  INDEX `fk_boleto_3_idx` (`id_descuento` ASC),
  CONSTRAINT `fk_boleto_1`
    FOREIGN KEY (`id_funcion`)
    REFERENCES `cineV2`.`funcion` (`id_funcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleto_2`
    FOREIGN KEY (`id_asiento`)
    REFERENCES `cineV2`.`asiento_sala` (`id_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleto_3`
    FOREIGN KEY (`id_descuento`)
    REFERENCES `cineV2`.`descuento` (`id_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cineV2`.`boleto_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`boleto_factura` (
  `id_boleto` INT(11) NOT NULL,
  `id_factura` INT(11) NOT NULL,
  PRIMARY KEY (`id_boleto`, `id_factura`),
  INDEX `fk_boletoPorFactura_1_idx` (`id_boleto` ASC),
  INDEX `fk_boletoPorFactura_2_idx` (`id_factura` ASC),
  CONSTRAINT `fk_boletoPorFactura_1`
    FOREIGN KEY (`id_boleto`)
    REFERENCES `cineV2`.`boleto` (`id_boleto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boletoPorFactura_2`
    FOREIGN KEY (`id_factura`)
    REFERENCES `cineV2`.`factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cineV2`.`orden_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cineV2`.`orden_factura` (
  `id_orden` INT(11) NOT NULL,
  `id_factura` INT(11) NOT NULL,
  PRIMARY KEY (`id_orden`, `id_factura`),
  INDEX `fk_orden_has_factura_factura1_idx` (`id_factura` ASC),
  INDEX `fk_orden_has_factura_orden1_idx` (`id_orden` ASC),
  CONSTRAINT `fk_orden_has_factura_orden1`
    FOREIGN KEY (`id_orden`)
    REFERENCES `cineV2`.`orden` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_has_factura_factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `cineV2`.`factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
