-- MySQL Script generated by MySQL Workbench
-- jue 29 ago 2019 16:59:58 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cine
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cine` ;

-- -----------------------------------------------------
-- Schema cine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cine` DEFAULT CHARACTER SET latin1 ;
USE `cine` ;

-- -----------------------------------------------------
-- Table `cine`.`asiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`asiento` ;

CREATE TABLE IF NOT EXISTS `cine`.`asiento` (
  `id_asiento` INT(11) NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_asiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`caracteristica_asiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`caracteristica_asiento` ;

CREATE TABLE IF NOT EXISTS `cine`.`caracteristica_asiento` (
  `id_caracteristica` INT(11) NOT NULL,
  `caracteristica` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_caracteristica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`atributo_asiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`atributo_asiento` ;

CREATE TABLE IF NOT EXISTS `cine`.`atributo_asiento` (
  `id_caracteristica` INT(11) NOT NULL,
  `id_asiento` INT(11) NOT NULL,
  `valor` INT(11) NOT NULL,
  INDEX `fk_atributo_asiento_caracteristica_asiento1_idx` (`id_caracteristica` ASC),
  INDEX `fk_atributo_asiento_asiento1_idx` (`id_asiento` ASC),
  PRIMARY KEY (`id_caracteristica`, `id_asiento`),
  CONSTRAINT `fk_atributo_asiento_asiento1`
    FOREIGN KEY (`id_asiento`)
    REFERENCES `cine`.`asiento` (`id_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atributo_asiento_caracteristica_asiento1`
    FOREIGN KEY (`id_caracteristica`)
    REFERENCES `cine`.`caracteristica_asiento` (`id_caracteristica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`caracteristica_funcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`caracteristica_funcion` ;

CREATE TABLE IF NOT EXISTS `cine`.`caracteristica_funcion` (
  `id_caracteristica` INT(11) NOT NULL,
  `caracteristica` VARCHAR(300) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_caracteristica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`clasificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`clasificacion` ;

CREATE TABLE IF NOT EXISTS `cine`.`clasificacion` (
  `id_clasificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `clasificacion` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_clasificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cine`.`director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`director` ;

CREATE TABLE IF NOT EXISTS `cine`.`director` (
  `id_director` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_director`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cine`.`pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`pelicula` ;

CREATE TABLE IF NOT EXISTS `cine`.`pelicula` (
  `id_pelicula` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NULL DEFAULT NULL,
  `duracion` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_estreno` DATE NULL DEFAULT NULL,
  `sinopsis` VARCHAR(500) NULL DEFAULT NULL,
  `id_director` INT(11) NOT NULL,
  `id_clasificacion` INT(11) NOT NULL,
  PRIMARY KEY (`id_pelicula`),
  INDEX `fk_pelicula_director1_idx` (`id_director` ASC),
  INDEX `fk_pelicula_clasificacion2_idx` (`id_clasificacion` ASC),
  CONSTRAINT `fk_pelicula_clasificacion2`
    FOREIGN KEY (`id_clasificacion`)
    REFERENCES `cine`.`clasificacion` (`id_clasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelicula_director1`
    FOREIGN KEY (`id_director`)
    REFERENCES `cine`.`director` (`id_director`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`funcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`funcion` ;

CREATE TABLE IF NOT EXISTS `cine`.`funcion` (
  `id_funcion` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `id_pelicula` INT(11) NOT NULL,
  PRIMARY KEY (`id_funcion`),
  INDEX `fk_funcion_pelicula1_idx` (`id_pelicula` ASC),
  CONSTRAINT `fk_funcion_pelicula1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `cine`.`pelicula` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`atributo_funcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`atributo_funcion` ;

CREATE TABLE IF NOT EXISTS `cine`.`atributo_funcion` (
  `id_caracteristica` INT(11) NOT NULL,
  `id_funcion` INT(11) NOT NULL,
  `valor` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_funcion`, `id_caracteristica`),
  INDEX `fk_atributo_funcion_caracteristica_funcion1_idx` (`id_caracteristica` ASC),
  INDEX `fk_atributo_funcion_funcion1_idx` (`id_funcion` ASC),
  CONSTRAINT `fk_atributo_funcion_caracteristica_funcion1`
    FOREIGN KEY (`id_caracteristica`)
    REFERENCES `cine`.`caracteristica_funcion` (`id_caracteristica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atributo_funcion_funcion1`
    FOREIGN KEY (`id_funcion`)
    REFERENCES `cine`.`funcion` (`id_funcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`caracteristica_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`caracteristica_sala` ;

CREATE TABLE IF NOT EXISTS `cine`.`caracteristica_sala` (
  `id_caracteristica` INT(11) NOT NULL AUTO_INCREMENT,
  `caracteristica` VARCHAR(300) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_caracteristica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`sucursal` ;

CREATE TABLE IF NOT EXISTS `cine`.`sucursal` (
  `id_sucursal` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `contacto` VARCHAR(45) NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cine`.`sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`sala` ;

CREATE TABLE IF NOT EXISTS `cine`.`sala` (
  `id_sala` INT(11) NOT NULL AUTO_INCREMENT,
  `sala` VARCHAR(45) NULL DEFAULT NULL,
  `id_sucursal` INT(11) NOT NULL,
  PRIMARY KEY (`id_sala`),
  INDEX `fk_sala_sucursal1_idx` (`id_sucursal` ASC),
  CONSTRAINT `fk_sala_sucursal1`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `cine`.`sucursal` (`id_sucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`atributo_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`atributo_sala` ;

CREATE TABLE IF NOT EXISTS `cine`.`atributo_sala` (
  `id_caracteristica` INT(11) NOT NULL,
  `id_sala` INT(11) NOT NULL,
  `valor` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_caracteristica`, `id_sala`),
  INDEX `fk_atributo_sala_caracteristica_sala_idx` (`id_caracteristica` ASC),
  INDEX `fk_atributo_sala_sala1_idx` (`id_sala` ASC),
  CONSTRAINT `fk_atributo_sala_caracteristica_sala`
    FOREIGN KEY (`id_caracteristica`)
    REFERENCES `cine`.`caracteristica_sala` (`id_caracteristica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atributo_sala_sala1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `cine`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`tipo_descuento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`tipo_descuento` ;

CREATE TABLE IF NOT EXISTS `cine`.`tipo_descuento` (
  `id_tipo_descuento` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `aplicable_boleto` TINYINT(1) NULL DEFAULT NULL,
  `aplicable_consumible` TINYINT(1) NULL DEFAULT NULL,
  `porcentaje_sugerido` DOUBLE NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_descuento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`descuento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`descuento` ;

CREATE TABLE IF NOT EXISTS `cine`.`descuento` (
  `id_descuento` INT(11) NOT NULL AUTO_INCREMENT,
  `porcentaje` DOUBLE NULL DEFAULT NULL,
  `id_tipo_descuento` INT(11) NOT NULL,
  PRIMARY KEY (`id_descuento`),
  INDEX `fk_descuento_tipo_descuento1_idx` (`id_tipo_descuento` ASC),
  CONSTRAINT `fk_descuento_tipo_descuento1`
    FOREIGN KEY (`id_tipo_descuento`)
    REFERENCES `cine`.`tipo_descuento` (`id_tipo_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`asiento_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`asiento_sala` ;

CREATE TABLE IF NOT EXISTS `cine`.`asiento_sala` (
  `id_asiento` INT(11) NOT NULL,
  `id_sala` INT(11) NOT NULL,
  `fila` VARCHAR(45) NOT NULL,
  `columna` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NULL,
  INDEX `fk_asiento_has_sala_sala1_idx` (`id_sala` ASC),
  INDEX `fk_asiento_has_sala_asiento1_idx` (`id_asiento` ASC),
  PRIMARY KEY (`id_asiento`),
  CONSTRAINT `fk_asiento_has_sala_asiento1`
    FOREIGN KEY (`id_asiento`)
    REFERENCES `cine`.`asiento` (`id_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asiento_has_sala_sala1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `cine`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`boleto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`boleto` ;

CREATE TABLE IF NOT EXISTS `cine`.`boleto` (
  `id_boleto` INT(11) NOT NULL AUTO_INCREMENT,
  `precio_base` DOUBLE NULL DEFAULT NULL,
  `id_funcion` INT(11) NOT NULL,
  `id_descuento` INT(11) NOT NULL,
  `id_asiento` INT(11) NOT NULL,
  PRIMARY KEY (`id_boleto`),
  INDEX `fk_boleto_funcion1_idx` (`id_funcion` ASC),
  INDEX `fk_boleto_descuento1_idx` (`id_descuento` ASC),
  INDEX `fk_boleto_asiento_sala1_idx` (`id_asiento` ASC),
  CONSTRAINT `fk_boleto_descuento1`
    FOREIGN KEY (`id_descuento`)
    REFERENCES `cine`.`descuento` (`id_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleto_funcion1`
    FOREIGN KEY (`id_funcion`)
    REFERENCES `cine`.`funcion` (`id_funcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleto_asiento_sala1`
    FOREIGN KEY (`id_asiento`)
    REFERENCES `cine`.`asiento_sala` (`id_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`orden` ;

CREATE TABLE IF NOT EXISTS `cine`.`orden` (
  `id_orden` INT(11) NOT NULL AUTO_INCREMENT,
  `monto_total` VARCHAR(45) NULL DEFAULT NULL,
  `id_descuento` INT(11) NOT NULL,
  PRIMARY KEY (`id_orden`),
  INDEX `fk_orden_descuento1_idx` (`id_descuento` ASC),
  CONSTRAINT `fk_orden_descuento1`
    FOREIGN KEY (`id_descuento`)
    REFERENCES `cine`.`descuento` (`id_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cine`.`tipo_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`tipo_pago` ;

CREATE TABLE IF NOT EXISTS `cine`.`tipo_pago` (
  `id_tipo_pago` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_pago` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`pago` ;

CREATE TABLE IF NOT EXISTS `cine`.`pago` (
  `id_pago` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NULL DEFAULT NULL,
  `id_tipo_pago` INT(11) NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_pago_tipo_pago1_idx` (`id_tipo_pago` ASC),
  CONSTRAINT `fk_pago_tipo_pago1`
    FOREIGN KEY (`id_tipo_pago`)
    REFERENCES `cine`.`tipo_pago` (`id_tipo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`factura` ;

CREATE TABLE IF NOT EXISTS `cine`.`factura` (
  `id_factura` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `id_pago` INT(11) NOT NULL,
  `id_orden` INT(11) NOT NULL,
  `id_boleto` INT(11) NOT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_factura_pago1_idx` (`id_pago` ASC),
  INDEX `fk_factura_orden2_idx` (`id_orden` ASC),
  INDEX `fk_factura_boleto1_idx` (`id_boleto` ASC),
  CONSTRAINT `fk_factura_orden2`
    FOREIGN KEY (`id_orden`)
    REFERENCES `cine`.`orden` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_pago1`
    FOREIGN KEY (`id_pago`)
    REFERENCES `cine`.`pago` (`id_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_boleto1`
    FOREIGN KEY (`id_boleto`)
    REFERENCES `cine`.`boleto` (`id_boleto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`genero` ;

CREATE TABLE IF NOT EXISTS `cine`.`genero` (
  `id_genero` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cine`.`genero_pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`genero_pelicula` ;

CREATE TABLE IF NOT EXISTS `cine`.`genero_pelicula` (
  `id_pelicula` INT(11) NOT NULL,
  `id_genero` INT(11) NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_genero`),
  INDEX `fk_pelicula_has_genero_genero1_idx` (`id_genero` ASC),
  INDEX `fk_pelicula_has_genero_pelicula1_idx` (`id_pelicula` ASC),
  CONSTRAINT `fk_pelicula_has_genero_genero1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `cine`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pelicula_has_genero_pelicula1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `cine`.`pelicula` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`menu_consumible`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`menu_consumible` ;

CREATE TABLE IF NOT EXISTS `cine`.`menu_consumible` (
  `id_consumible` INT(11) NOT NULL,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_consumible`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cine`.`orden_consumible`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cine`.`orden_consumible` ;

CREATE TABLE IF NOT EXISTS `cine`.`orden_consumible` (
  `id_orden` INT(11) NOT NULL,
  `id_consumible` INT(11) NOT NULL,
  `cantidad` INT(4) NOT NULL,
  `monto_total` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_orden`, `id_consumible`),
  INDEX `fk_orden_consumible_menu_consumible1_idx` (`id_consumible` ASC),
  INDEX `fk_orden_consumible_orden2_idx` (`id_orden` ASC),
  CONSTRAINT `fk_orden_consumible_menu_consumible1`
    FOREIGN KEY (`id_consumible`)
    REFERENCES `cine`.`menu_consumible` (`id_consumible`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_consumible_orden2`
    FOREIGN KEY (`id_orden`)
    REFERENCES `cine`.`orden` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
